name: CI Pipeline

on:
  push:
    branches:
      - main  # Roda a pipeline sempre que há um push na branch principal
  pull_request:
    branches:
      - main  # Roda a pipeline para cada pull request na branch principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usa um ambiente Ubuntu no GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Faz o checkout do código do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Define a versão do Node.js (ajuste conforme necessário)

      - name: Install dependencies
        run: npm install  # Instala as dependências da aplicação

      - name: Run tests
        run: npm test  # Executa os testes definidos na aplicação

      - name: Build application
        run: npm run build  # Compila a aplicação

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/  # Define o diretório dos artefatos de build
